language: cpp

branches:
    only:
        - 4-write-documentation

matrix:
  include:
    - os: windows
      env:
          - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
          - VULKAN_SDK="C:\VulkanSDK\1.2.170.0"
      before_install:
          - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
          - choco install dotnetcore-sdk
          - dotnet restore
          - git clone https://github.com/microsoft/vcpkg
          - ./vcpkg/bootstrap-vcpkg.bat

      install:
          - curl -L --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.2.170.0/windows/VulkanSDK-1.2.170.0-Installer.exe
          - ./VulkanSDK.exe /SA
          - ./vcpkg/vcpkg install --triplet x64-windows gli glm libpng libjpeg-turbo ranve-v3 ms-gsl vulkan-sdk

      build:
          - meson builddir 
          - ninja -C builddir -j8

      cache:
         directories:
              - $HOME/vcpkg
              - $VULKAN_SDK
