if(CMAKE_VERSION VERSION_LESS 3.5.2)
    include(CMakeParseArguments)
endif()

set(FIND_STORMKIT_DEPENDENCIES_NOTFOUND)
if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    set(FIND_STORMKIT_OS_WINDOWS 1)
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    set(FIND_STORMKIT_OS_LINUX 1)
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(FIND_STORMKIT_OS_MACOS 1)
elseif(${CMAKE_SYSTEM_NAME} MATCHES "iOS")
    set(FIND_STORMKIT_OS_IOS 1)
endif()

function(stormkit_bind_dependency)
    cmake_parse_arguments(THIS "" "TARGET" ${ARGN})

    if (THIS_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Unknown arguments when calling stormkit_bind_dependency: ${THIS_UNPARSED_ARGUMENTS}")
    endif()

    find_package(${THIS_TARGET})

    if(TARGET ${THIS_TARGET})
    else()
        set(FIND_STORMKIT_DEPENDENCIES_NOTFOUND "${FIND_STORMKIT_DEPENDENCIES_NOTFOUND}" PARENT_SCOPE)
    endif()
endfunction()

list(FIND STORMKIT_FIND_COMPONENTS "Core" FIND_STORMKIT_CORE_COMPONENT_INDEX)
if(FIND_STORMKIT_CORE_COMPONENT_INDEX GREATER -1)
    stormkit_bind_dependency(TARGET fmt)
    stormkit_bind_dependency(TARGET glm)
    stormkit_bind_dependency(TARGET Microsoft.GSL)
    stormkit_bind_dependency(TARGET range-v3)
endif()

list(FIND STORMKIT_FIND_COMPONENTS "Render" FIND_STORMKIT_RENDER_COMPONENT_INDEX)
if(FIND_STORMKIT_RENDER_COMPONENT_INDEX GREATER -1)
    stormkit_bind_dependency(TARGET Vulkan)
endif()

if(STORMKIT_STATIC_LIBRARIES)
    list(FIND STORMKIT_FIND_COMPONENTS "Image" FIND_STORMKIT_IMAGE_COMPONENT_INDEX)
    if(FIND_STORMKIT_IMAGE_COMPONENT_INDEX GREATER -1)
        stormkit_bind_dependency(TARGET PNG)
        stormkit_bind_dependency(TARGET JPEG)
    endif()
endif()
