function(enable_cpp17 TARGET COMPILER)
    target_compile_features(${TARGET} PUBLIC cxx_std_20)
    set_target_properties(${TARGET} PROPERTIES CXX_EXTENSIONS OFF)
    if(COMPILER MATCHES "MSVC")
        target_compile_definitions(${TARGET} PUBLIC "NOMINMAX")
    endif()
endfunction()

function(enable_sanitizers TARGET)
    set_target_properties(${TARGET} PROPERTIES CMAKE_CXX_FLAGS "-fsanitize=address -fsanitize=undefined")
endfunction()
