include(CheckIncludeFileCXX)
include(CheckTypeSize)
include(CheckIPOSupported)

function(detect_os)
    set(STORM_OS "" PARENT_SCOPE)
    set(STORM_OS_WIN32 OFF PARENT_SCOPE)
    set(STORM_OS_APPLE OFF PARENT_SCOPE)
    set(STORM_OS_MACOS OFF PARENT_SCOPE)
    set(STORM_OS_POSIX OFF PARENT_SCOPE)
    set(STORM_OS_LINUX OFF PARENT_SCOPE)
    set(STORM_OS_NX OFF PARENT_SCOPE)

    if(CMAKE_SYSTEM_NAME MATCHES "Windows")
        set(STORM_OS "Win32" PARENT_SCOPE)
        set(STORM_OS_WIN32 ON PARENT_SCOPE)
    elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
        set(STORM_OS "Linux" PARENT_SCOPE)
        set(STORM_OS_POSIX ON PARENT_SCOPE)
        set(STORM_OS_LINUX ON PARENT_SCOPE)
    elseif(CMAKE_SYSTEM_NAME MATCHES "Darwin")
        set(STORM_OS "macOS" PARENT_SCOPE)
        set(STORM_OS_POSIX ON PARENT_SCOPE)
        set(STORM_OS_MACOS ON PARENT_SCOPE)
        set(STORM_OS_APPLE ON PARENT_SCOPE)
    elseif(CMAKE_SYSTEM_NAME MATCHES "Generic")
        if(${SWITCH})
        set(STORM_OS "Nintendo Switch" PARENT_SCOPE)
        set(STORM_OS_POSIX ON PARENT_SCOPE)
        endif()
    endif()
endfunction()

function(detect_cpp_compiler)
    set(STORM_COMPILER "MSVC" PARENT_SCOPE)
    set(STORM_COMPILER_CLANG OFF PARENT_SCOPE)
    set(STORM_COMPILER_GCC OFF PARENT_SCOPE)
    set(STORM_COMPILER_MSVC OFF PARENT_SCOPE)

    if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        set(STORM_COMPILER "MSVC" PARENT_SCOPE)
        set(STORM_COMPILER_MSVC ON PARENT_SCOPE)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID MATCHES "AppleClang")
        set(STORM_COMPILER "Clang" PARENT_SCOPE)
        set(STORM_COMPILER_CLANG ON PARENT_SCOPE)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
        set(STORM_COMPILER "GCC" PARENT_SCOPE)
        set(STORM_COMPILER_GCC ON PARENT_SCOPE)
    endif()
endfunction()

function(detect_cpp_types)
    set(type_check_includes ${type_check_includes} cstdint)
    set(type_check_includes ${type_check_includes} cstddef)

    check_type_size(char CHAR_T LANGUAGE CXX)
    check_type_size(short SHORT_T LANGUAGE CXX)
    check_type_size(int INT_T LANGUAGE CXX)
    check_type_size(long LONG_T LANGUAGE CXX)
    check_type_size("long long" LONGLONG_T LANGUAGE CXX)
    check_type_size(float FLOAT_T LANGUAGE CXX)
    check_type_size(double DOUBLE_T LANGUAGE CXX)

    check_type_size(int8_t INT8_T LANGUAGE CXX)
    check_type_size(uint8_t UINT8_T LANGUAGE CXX)
    check_type_size(int16_t INT16_T LANGUAGE CXX)
    check_type_size(uint16_t UINT16_T LANGUAGE CXX)
    check_type_size(int32_t INT32_T LANGUAGE CXX)
    check_type_size(uint32_t UINT32_T LANGUAGE CXX)
    check_type_size(int64_t INT64_T LANGUAGE CXX)
    check_type_size(uint64_t UINT64_T LANGUAGE CXX)

    check_type_size(intptr_t INTPTR_T  LANGUAGE CXX)
    check_type_size(uintptr_t UINTPTR_T  LANGUAGE CXX)
    check_type_size(ptrdiff_t PTRDIFF_T  LANGUAGE CXX)
    check_type_size(size_t SIZE_T LANGUAGE CXX)
endfunction()

function(detect_cpp_headers)
    set(CXX_HEADER_NEEDED iostream exception string sstream stdexcept cfloat cstdint cstddef algorithm)
    set(CXX14_HEADER_NEEDED type_traits memory random functional regex)
    set(CXX17_HEADER_NEEDED any optional filesystem variant)
    set(CXX17_HEADER_EXP_NEEDED)

    foreach(INCLUDE_FILE IN LISTS CXX_HEADER_NEEDED)
        string(TOUPPER ${INCLUDE_FILE} INCLUDE_FILE_UPPER)
        check_include_file_cxx("${INCLUDE_FILE}" HAVE_${INCLUDE_FILE_UPPER})

        if(NOT HAVE_${INCLUDE_FILE_UPPER})
            message(FATAL_ERROR "Error: Can't find ${INCLUDE_FILE} standard include file")
        endif(NOT HAVE_${INCLUDE_FILE_UPPER})
    endforeach()

    foreach(INCLUDE_FILE IN LISTS CXX14_HEADER_NEEDED)
        string(TOUPPER ${INCLUDE_FILE} INCLUDE_FILE_UPPER)
        check_include_file_cxx("${INCLUDE_FILE}" HAVE_${INCLUDE_FILE_UPPER})
        if(NOT HAVE_${INCLUDE_FILE_UPPER})
            message(FATAL_ERROR "Error: Can't find ${INCLUDE_FILE} standard include file")
        endif(NOT HAVE_${INCLUDE_FILE_UPPER})
    endforeach()

    foreach(INCLUDE_FILE IN LISTS CXX17_HEADER_NEEDED)
        string(TOUPPER ${INCLUDE_FILE} INCLUDE_FILE_UPPER)
        check_include_file_cxx("${INCLUDE_FILE}" HAVE_${INCLUDE_FILE_UPPER})
        if(NOT HAVE_${INCLUDE_FILE_UPPER})
            list(APPEND CXX17_HEADER_EXP_NEEDED experimental/${INCLUDE_FILE})
        endif()
    endforeach()

    foreach(INCLUDE_FILE IN LISTS CXX17_HEADER_EXP_NEEDED)
        string(TOUPPER ${INCLUDE_FILE} INCLUDE_FILE_UPPER)
        check_include_file_cxx("${INCLUDE_FILE}" HAVE_${INCLUDE_FILE_UPPER})
    endforeach()
endfunction()
