set(SWITCH TRUE)

set(CMAKE_CROSSCOMPILING TRUE CACHE STRING "" FORCE)
set(CMAKE_SYSTEM_NAME Generic CACHE STRING "" FORCE)
set(CMAKE_SYSTEM_PROCESSOR aarch64 CACHE STRING "" FORCE)

set(TARGET aarch64-armv8a-switch-elf CACHE STRING "" FORCE)

set(LLVM_TOOLCHAIN_PATH $ENV{LLVM_TOOLCHAIN_PATH} CACHE STRING "" FORCE)
set(LLVM_TOOLCHAIN_BIN_PATH ${LLVM_TOOLCHAIN_PATH}/bin CACHE STRING "" FORCE)
set(LLVM_TOOLCHAIN_INCLUDE_PATH ${LLVM_TOOLCHAIN_PATH}/include CACHE STRING "" FORCE)
set(LLVM_TOOLCHAIN_LIB_PATH ${LLVM_TOOLCHAIN_PATH}/lib CACHE STRING "" FORCE)

set(DEVKITPRO     $ENV{DEVKITPRO} CACHE STRING "" FORCE)
set(LIBNX         ${DEVKITPRO}/libnx CACHE STRING "" FORCE)
set(PORTLIBS_PATH ${DEVKITPRO}/portlibs CACHE STRING "" FORCE)
set(PORTLIBS      ${PORTLIBS_PATH}/switch CACHE STRING "" FORCE)

set(PKG_CONFIG_EXECUTABLE ${TOOLCHAIN_PREFIX}pkg-config${TOOLCHAIN_SUFFIX} CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH  ${LLVM_TOOLCHAIN_PATH} ${LIBNX} ${PORTLIBS} CACHE STRING "" FORCE)
 
set(CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN   ${LLVM_TOOLCHAIN_PATH} CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN ${LLVM_TOOLCHAIN_PATH} CACHE STRING "" FORCE)
 
set(CMAKE_C_COMPILER          ${LLVM_TOOLCHAIN_BIN_PATH}/clang CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER_TARGET   ${TARGET} CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER        ${LLVM_TOOLCHAIN_BIN_PATH}/clang++ CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER_TARGET ${TARGET} CACHE STRING "" FORCE)
set(CMAKE_ASM_COMPILER        ${LLVM_TOOLCHAIN_BIN_PATH}/llvm-mc CACHE STRING "" FORCE)
set(CMAKE_ASM_COMPILER_TARGET ${TARGET} CACHE STRING "" FORCE)
set(CMAKE_AR                  ${LLVM_TOOLCHAIN_BIN_PATH}/llvm-ar CACHE STRING "" FORCE)
set(CMAKE_RANLIB              ${LLVM_TOOLCHAIN_BIN_PATH}/llvm-ranlib CACHE STRING "" FORCE)
set(CMAKE_LD                  ${LLVM_TOOLCHAIN_BIN_PATH}/ld.lld CACHE STRING "" FORCE)
set(CMAKE_OBJCOPY             ${LLVM_TOOLCHAIN_BIN_PATH}/llvm-objcopy CACHE STRING "" FORCE)
set(CMAKE_SIZE_UTIL           ${LLVM_TOOLCHAIN_BIN_PATH}/llvm-size CACHE STRING "" FORCE)
set(CMAKE_TOOLCHAIN_PREFIX    llvm-  CACHE STRING "" FORCE)

add_definitions(-D__SWITCH__)

set(C_INCLUDES   "-isystem ${LLVM_TOOLCHAIN_INCLUDE_PATH}/" CACHE STRING "" FORCE)
set(CXX_INCLUDES "-isystem ${LLVM_TOOLCHAIN_INCLUDE_PATH}/c++/v1/" CACHE STRING "" FORCE)

set(ARCH      "-target ${TARGET} -march=armv8-a -mtune=cortex-a53" CACHE STRING "" FORCE)
set(C_FLAGS   "-DLIBCXX_USE_COMPILER_RT=YES -fPIE -fuse-ld=lld -nostdlib -nostdlibinc ${C_INCLUDES}" CACHE STRING "" FORCE)
set(CXX_FLAGS "-stdlib=libc++ -nodefaultlibs -nostdinc++ -fno-exceptions -fno-rtti ${CXX_INCLUDES}" CACHE STRING "" FORCE)
set(ASMFLAGS  "-arch=aarch64 -triple aarch64-none-elf" CACHE STRING "" FORCE)
set(LD_FLAGS  "-fuse-ld=lld ${ARCH} -L${LLVM_TOOLCHAIN_LIB_PATH} -T${CMAKE_CURRENT_SOURCE_DIR}/cmake/Toolchains/switch-ld/link.ld --shared -Bsymbolic" CACHE STRING "" FORCE)

set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS} ${ARCH} ${C_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CMAKE_C_FLAGS} ${CXX_FLAGS} " CACHE STRING "" FORCE)

set(CMAKE_C_ARCHIVE_CREATE   "${CMAKE_C_ARCHIVE_CREATE} rcs" CACHE STRING "" FORCE)
set(CMAKE_CXX_ARCHIVE_CREATE "${CMAKE_CXX_ARCHIVE_CREATE} rcs" CACHE STRING "" FORCE)

set(CMAKE_EXE_LINKER_FLAGS_INIT    "${LD_FLAGS} -Bstatic -Bdynamic" CACHE STRING "" FORCE)
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${LD_FLAGS} -Bdynamic" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${LD_FLAGS} -Bdynamic" CACHE STRING "" FORCE)
set(CMAKE_STATIC_LINKER_FLAGS_INIT "${LD_FLAGS}" CACHE STRING "" FORCE)

/opt/aarch64-llvm/bin/clang++ -target aarch64-armv8a-switch-elf -march=armv8-a -mtune=cortex-a53 -std=c++17 -stdlib=libc++ -isystem /opt/aarch64-llvm/include/c++/v1/ -isystem /opt/aarch64-llvm/include -DLIBCXX_USE_COMPILER_RT=YES -fPIE -fno-exceptions -fno-rtti file.cp
