name: Archlinux

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '.github/workflows/Ubuntu.yml'
      - '.github/workflows/Windows.yml'
      - '.github/workflows/Fedora.yml'
      - '.github/workflows/macOS.yml'
      - '.github/workflows/iOS.yml'
      - '.github/workflows/Android.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches: [ main, dev ]
    paths-ignore:
      - '.github/workflows/Ubuntu.yml'
      - '.github/workflows/Windows.yml'
      - '.github/workflows/Fedora.yml'
      - '.github/workflows/macOS.yml'
      - '.github/workflows/iOS.yml'
      - '.github/workflows/Android.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    name: archlinux-latest-x64 ( ${{ matrix.kind }}-${{ matrix.mode }} )

    strategy:
      fail-fast: false
      matrix:
        os: [archlinux]
        kind: [static, shared]
        mode: [release, debug, asan]

    runs-on: self-hosted

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Archlinux-${{ matrix.kind }}-${{ matrix.mode }}

    steps:
      - name: Dependencies bootstrap
        run: |
          pacman -Syu --noconfirm --needed openssl
          pacman -Sy --noconfirm --needed glibc git base-devel perl make unzip p7zip
          pacman -Sy --noconfirm --needed mesa gcc-fortran glu wget
          wget https://github.com/Arthapz/llvm-18-patched/raw/main/arch/libc++-git-18.0.0_r476929.7a46baa465c4-1-x86_64.pkg.tar.zst
          wget https://github.com/Arthapz/llvm-18-patched/raw/main/arch/libc++abi-git-18.0.0_r476929.7a46baa465c4-1-x86_64.pkg.tar.zst
          wget https://github.com/Arthapz/llvm-18-patched/raw/main/arch/llvm-git-18.0.0_r476929.7a46baa465c4-1-x86_64.pkg.tar.zst
          wget https://github.com/Arthapz/llvm-18-patched/raw/main/arch/llvm-libs-git-18.0.0_r476929.7a46baa465c4-1-x86_64.pkg.tar.zst
          pacman --noconfirm -U *.zst 

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install v
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: Update xmake repository
        run: sudo xmake repo --root -vD --update

      - name: Configure & Build
        id: build
        run: |
          xmake f -vD --yes -m ${{ matrix.mode }} -k ${{ matrix.kind }} --toolchain=llvm --sdk=/opt/llvm-git/usr
          xmake b -vD

      - name: Tests
        run: xmake run core-tests --verbose

      - name: Installation
        run: xmake install -vD --installdir="/output"

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v1
        with:
          name: Archlinux-x64-${{ matrix.kind }}-${{ matrix.mode }}
          path: /output
