name: CI StormKit Nightly

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build-ubuntu:
    name: ${{ matrix.os.name }} ${{ matrix.library_type }}, ${{ matrix.build_type }} )
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - {
           name: "Ubuntu ( G++10,",
           osname: "Ubuntu",
           value: ubuntu-latest
        }
            
        library_type: [static, shared]
        build_type: [release, debug]
    
    steps:
        - name: Install apt deps
          id: aptdeps
          run: |
            wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
            sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list https://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo add-apt-repository -y ppa:deadsnakes/ppa
            sudo apt -q update
            sudo apt -y install vulkan-sdk \
              gcc-10 \
              g++-10 \
              libxcb-util0-dev \
              tar \
              curl \
              zip \
              unzip \
              libxcb-xinput-dev \
              libwayland-dev \
              python3.9 \
              libxkbcommon-dev \
              libxkbcommon-x11-dev \
              libxcb-randr0-dev \
              libxcb1-dev \
              libxcb-icccm4-dev \
              libxcb-xkb-dev \
              libxcb-keysyms1-dev \
              libxcb-xfixes0-dev
            sudo pip3 install meson ninja
          
        - name: Install vcpkg deps
          uses: lukka/run-vcpkg@v6
          id: runvcpkg
          with:
            vcpkgArguments: libpng libjpeg-turbo glm gli fmt rapidjson range-v3 ms-gsl
            vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
            vcpkgGitCommitId: fddf97411017bfcd7dd988d754b25efc3d6a1c3e
            vcpkgTriplet: x64-linux
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
            
        - name: Configure & Build
          id: confandbuild
          run: |
            export CC=gcc-10
            export CXX=g++-10
            meson builddir \
              -Denable_examples=true \
              -Dexamples_data_dir="../share/" \
              -Dbuildtype=${{ matrix.build_type }} \
              -Dlibrary_type=${{ matrix.library_type }} \
              --cmake-prefix-path ${{ runner.workspace }}/vcpkg/installed/x64-linux/ \
              --prefix=${{ runner.workspace }}/StormKit_Output
            ninja -C builddir -j8

        - name: Install
          id: install
          run: |
            ninja -C builddir install -j8

        - name: Upload artifacts
          id: upload
          uses: actions/upload-artifact@v1
          with:
            name: ${{ matrix.os.osname }}-GCC10-${{ matrix.library_type }}-${{ matrix.build_type }}
            path: ${{ runner.workspace }}/StormKit_Output
  build-windows:
    name: ${{ matrix.os.name }} ${{ matrix.library_type }}, ${{ matrix.build_type }} )
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - {
           name: "Windows ( MSVC19, ",
           osname: "Windows",
           value: windows-latest
        }

        library_type: [static, shared]
        build_type: [release, debug]

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: Install meson
        id: installmeson
        run: |
          pip install meson ninja

      - name: Install vcpkg deps
        uses: lukka/run-vcpkg@v6
        id: runvcpkg
        with:
          vcpkgArguments: libpng libjpeg-turbo glm gli fmt rapidjson range-v3 ms-gsl
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
          vcpkgGitCommitId: fddf97411017bfcd7dd988d754b25efc3d6a1c3e
          vcpkgTriplet: x64-windows

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Configure & Build
        id: confandbuild
        run: |
          meson builddir \
            -Denable_examples=true \
            -Dexamples_data_dir="../share/" \
            -Dbuildtype=${{ matrix.build_type }} \
            -Dlibrary_type=${{ matrix.library_type }} \
            --cmake-prefix-path ${{ runner.workspace }}/vcpkg/installed/x64-windows/ \
            --prefix=${{ runner.workspace }}/StormKit_Output
          ninja -C builddir -j8

      - name: Install
        id: install
        run: |
          ninja -C builddir install -j8

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os.osname }}-MSVC19-${{ matrix.library_type }}-${{ matrix.build_type }}
          path: ${{ runner.workspace }}/StormKit_Output


