name: Linux

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: ${{ matrix.os.name }} ( ${{matrix.os.compiler }} ${{ matrix.library_type }}, ${{ matrix.build_type }} )
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - {
           name: "Ubuntu",
           compiler: "GCC",
           value: ubuntu-22.04,
           triplet: "x64-linux"
        }
            
        library_type: [static, shared]
        build_type: [release, debug]
    env:
      VCPKG_FEATURE_FLAGS: "binarycaching"
      CC: "gcc-12"
      CXX: "g++-12"
    steps:
        - name: Install apt deps
          id: aptdeps
          run: |
            wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
            sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list https://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo add-apt-repository -y ppa:deadsnakes/ppa
            sudo apt -q update
            sudo apt -y install vulkan-sdk \
              gcc-12 \
              g++-12 \
              libxcb-util0-dev \
              tar \
              curl \
              zip \
              unzip \
              libxcb-xinput-dev \
              libwayland-dev \
              libxkbcommon-dev \
              libxkbcommon-x11-dev \
              libxcb-randr0-dev \
              libxcb1-dev \
              libxcb-icccm4-dev \
              libxcb-xkb-dev \
              libxcb-keysyms1-dev \
              libxcb-xfixes0-dev \
              cmake \
              meson \
              ninja-build

        - name: Install xmake
          run: |
            bash <(curl -fsSL https://xmake.io/shget.text)

        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
            
        - name: Configure & Build
          id: confandbuild
          run: |
            xmake f -v --yes -m ${{ matrix.build_type }} -k ${{ matrix.library_type }}
            xmake b

        - name: Install
          id: install
          run: |
            xmake install --installdir="${{ runner.workspace }}/StormKit_Output"

        - name: Upload artifacts
          id: upload
          uses: actions/upload-artifact@v1
          with:
            name: ${{ matrix.os.name }}-${{ matrix.os.compiler }}-${{ matrix.library_type }}-${{ matrix.build_type }}
            path: ${{ runner.workspace }}/StormKit_Output
 