name: macOS

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    name: ${{ matrix.os.name }} ( ${{matrix.os.compiler }} ${{ matrix.library_type }}, ${{ matrix.build_type }} )
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
        #- {
        #   name: "macOS 11",
        #   compiler: "LLVM 13",
        #   value: macos-11.0,
        #   triplet: "x64-macos"
        #}

        - {
           name: "macOS 10.15",
           compiler: "LLVM 13",
           value: macos-10.15,
           triplet: "x64-osx"
        }
            
        library_type: [static, shared]
        build_type: [release, debug]
    env:
      VCPKG_FEATURE_FLAGS: "binarycaching"
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            lfs: true
            fetch-depth: 0

        - name: Install python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
            architecture: 'x64'

        - name: Install meson and ninja
          run: |
            pip3 install meson ninja

        - name: Install brew dependencies
          run: |
            brew update
            brew tap apenngrace/homebrew-vulkan
            brew install vulkan-sdk wget p7zip

        - name: Retrieve and Extract LLVM13
          run: |
            wget -q https://gitlab.com/Arthapz/llvm13-macos/-/raw/master/LLVM13.7z?inline=false -O ${{ runner.workspace }}/LLVM13.7z
            7z x ${{ runner.workspace }}/LLVM13.7z
            ls ${{ runner.workspace }}

        - name: Configure native file
          run: |
            cp ${{ runner.workspace }}/StormKit/macos-llvm13-clang.ini.sample ${{ runner.workspace }}/StormKit/macos-llvm13-clang.ini
            sed -i -e 's|%TOOLCHAIN_PATH%|${{ runner.workspace }}/StormKit/LLVM13.0.0git.xctoolchain/usr|g' ${{ runner.workspace }}/StormKit/macos-llvm13-clang.ini

        - uses: lukka/get-cmake@latest
        - name: Setup vcpkg
          uses: lukka/run-vcpkg@v6
          id: runvcpkg
          with:
            vcpkgArguments: libpng libjpeg-turbo glm gli fmt rapidjson range-v3 ms-gsl
            vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
            vcpkgGitCommitId: fddf97411017bfcd7dd988d754b25efc3d6a1c3e
            vcpkgTriplet: ${{ matrix.os.triplet }}
            
        - name: Configure & Build
          id: confandbuild
          run: |
            meson builddir  \
              --native-file ${{ runner.workspace }}/StormKit/macos-llvm13-clang.ini \
              -Denable_examples=true \
              -Dexamples_data_dir="../share/" \
              -Dbuildtype=${{ matrix.build_type }} \
              -Dlibrary_type=${{ matrix.library_type }} \
              --cmake-prefix-path=${{ runner.workspace }}/vcpkg/installed/${{ matrix.os.triplet }}/ \
              --prefix=${{ runner.workspace }}/StormKit_Output
            ninja -C builddir -j7

        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: fail-${{ matrix.os.name }}-{{ matrix.library_type }}-${{ matrix.build_type }}-meson-log
            path: builddir/meson-logs/testlog.txt

        - name: Install
          id: install
          run: |
            ninja -C builddir install -j7

        - name: Upload artifacts
          id: upload
          uses: actions/upload-artifact@v1
          with:
            name: ${{ matrix.os.name }}-${{ matrix.os.compiler }}-${{ matrix.library_type }}-${{ matrix.build_type }}
            path: ${{ runner.workspace }}/StormKit_Output
 