name: macOS

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: ${{ matrix.os.name }} ( ${{matrix.os.compiler }} ${{ matrix.library_type }}, ${{ matrix.build_type }} )
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - {
           name: "macOS 11",
           compiler: "LLVM",
           value: macos-latest,
           triplet: "x64-macos"
        }

        library_type: [static, shared]
        build_type: [release, debug]
    env:
      VCPKG_FEATURE_FLAGS: "binarycaching"
    steps:
        - name: Install brew dependencies
          run: |
            brew update
            brew tap apenngrace/homebrew-vulkan
            brew install vulkan-sdk wget p7zip curl xmake

        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Configure & Build
          id: confandbuild
          run: |
            xmake f -v --yes -m ${{ matrix.build_type }} -k ${{ matrix.library_type }}
            xmake b

        - name: Install
          id: install
          run: |
            xmake install --installdir="${{ runner.workspace }}/StormKit_Output"

        - name: Upload artifacts
          id: upload
          uses: actions/upload-artifact@v1
          with:
            name: ${{ matrix.os.name }}-${{ matrix.os.compiler }}-${{ matrix.library_type }}-${{ matrix.build_type }}
            path: ${{ runner.workspace }}/StormKit_Output