name: Windows

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: ${{ matrix.os.name }} ( ${{matrix.os.compiler }} ${{ matrix.library_type }}, ${{ matrix.build_type }} )
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - {
           name: "Windows",
           compiler: "MSVC",
           value: windows-latest,
           triplet: "x64-windows"
        }
        - {
           name: "Windows",
           compiler: "MinGW",
           value: windows-latest,
           triplet: "x64-windows"
        }
            
        library_type: [static, shared]
        build_type: [release, debug]
    steps:
        - name: Install msvc
          uses: ilammy/msvc-dev-cmd@v1

        - name: Install xmake
          run: |
            Invoke-Expression (Invoke-Webrequest 'https://xmake.io/psget.text' -UseBasicParsing).Content
            if("${{ matrix.os.compiler }}" == "MinGW") {
              xrepo install llvm-mingw
            } 

        - name: Configure & Build
          id: confandbuild
          run: |
            if("${{ matrix.os.compiler }}" == "MinGW") {
              xmake f -v --yes -m ${{ matrix.build_type }} -k ${{ matrix.library_type }} -p mingw@llvm-mingw
            else
              xmake f -v --yes -m ${{ matrix.build_type }} -k ${{ matrix.library_type }}
            }
            xmake b

        - name: Install
          id: install
          run: |
            xmake install --installdir="${{ runner.workspace }}/StormKit_Output"

            
        - name: Upload artifacts
          id: upload
          uses: actions/upload-artifact@v1
          with:
            name: ${{ matrix.os.name }}-${{ matrix.os.compiler }}-${{ matrix.library_type }}-${{ matrix.build_type }}
            path: ${{ runner.workspace }}/StormKit_Output
 