name: Windows

on:
  push:
    branches: [develop]
    paths-ignore:
      - '.github/workflows/Linux.yml'
      - '.github/workflows/macOS.yml'
      - '.github/workflows/iOS.yml'
      - '.github/workflows/Android.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - '.github/workflows/Linux.yml'
      - '.github/workflows/macOS.yml'
      - '.github/workflows/iOS.yml'
      - '.github/workflows/Android.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.arch }} ( ${{ matrix.kind }}-${{ matrix.mode }}-${{ matrix.vs_runtime }} )

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        compiler: [llvm]
        kind: [static, shared]
        mode: [release, debug, asan]
        vs_runtime: [MT, MD]
        arch: [x64]

    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Windows-${{ matrix.compiler }}-${{ matrix.kind }}-${{ matrix.mode }}-${{ matrix.vs_runtime }}

    steps:
      - name: Get current date as package key
        id: cache-key
        run: echo "key=$(date +'%W')" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set xmake env
        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev
          actions-cache-folder: .xmake-cache-W${{ steps.cache_key.outputs.key }}

      - name: Update xmake repository
        run: xmake repo --update

      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.3
        with:
          minimum-size: 8GB
          maximum-size: 32GB
          disk-root: "D:"

      - name: Retrieve dependencies hash
        id: dep-hash
        run: echo "hash=$(xmake l utils.ci.packageskey)" >> $GITHUB_OUTPUT

      - name: Retrieve cached xmake dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: Windows-${{ matrix.compiler }}-${{ matrix.mode }}-${{ steps.dep_hash.outputs.hash }}-W${{ steps.cache_key.outputs.key }}

      - name: Cache LLVM
        id: cache-llvm
        if: ${{ matrix.compiler == 'llvm' }}
        uses: actions/cache@v3
        env:
          cache-name: cache-llvm
        with:
          path: llvm
          key: Windows-${{ env.cache-name }}-llvm
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-llvm

      - name: Download LLVM
        uses: wei/wget@v1
        if: ${{ matrix.compiler == 'llvm' && steps.cache-llvm.outputs.cache-hit != 'true' }}
        with:

      - name: Download and Uncompress LLVM
        if: ${{ matrix.compiler == 'llvm' && steps.cache-llvm.outputs.cache-hit != 'true' }}
        run: |
          C:/msys64/bin/wget.exe http://86.221.35.29:1337/llvm-win.7z
          7z x llvm-win.7z

      - name: Configure & Build
        id: build_msvc
        if: ${{ matrix.compiler == 'msvc' }}
        run: |
          {{  }}
          xmake f -vD --yes -a ${{ matrix.arch }}  -m ${{ (matrix.mode == 'release' || matrix.mode == 'debug') && matrix.mode || 'releasedbg' }} -k ${{ matrix.kind }} --vs_runtime=${{ matrix.vs_runtime }} --enable_examples=y --enable_tests=y --enable_gpu=n
          xmake b -vD

      - name: Configure & Build
        id: build_llvm
        if: ${{ matrix.compiler == 'llvm' }}
        run: |
          {{  }}
          xmake f -vD --yes -a ${{ matrix.arch }}  -m ${{ (matrix.mode == 'release' || matrix.mode == 'debug') && matrix.mode || 'releasedbg' }} -k ${{ matrix.kind }} --vs_runtime=${{ matrix.vs_runtime }} --enable_examples=y --enable_tests=y --enable_gpu=n --libc++=y --toolchain=llvm --sdk="$PWD/llvm/" --libc++=y --cxxflags="-fno-delayed-template-parsing "-cxx-isystem$PWD/llvm/include/c++/v1" --ldflags="-L$PWD/llvm/lib" --shflags="-L$PWD/llvm/lib"
          xmake b -vD

      - name: Tests
        if: ${{ matrix.compiler == 'msvc' }}
        run: |
          xmake test -vD

      - name: Tests
        if: ${{ matrix.compiler == 'llvm' }}
        run: |
          set PATH=%PATH%;$PWD/llvm/lib
          xmake test -vD

      - name: Installation
        run: xmake install -vD --installdir="${{ runner.workspace }}/output"

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.arch }}-${{ matrix.kind }}-${{ matrix.mode }}-${{ matrix.vs_runtime }}
          path: ${{ runner.workspace }}/output
