name: Windows

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: ${{ matrix.os.name }} ( ${{matrix.os.compiler }} ${{ matrix.kind }}, ${{ matrix.build_type }} )
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - {
           name: "Windows",
           compiler: "MSVC",
           value: windows-latest,
           triplet: "x64-windows"
        }
        - {
           name: "Windows",
           compiler: "MinGW",
           value: windows-latest,
           triplet: "x64-windows"
        }
            
        kind: [static, shared]
        build_type: [release, debug]
    steps:
        - name: Install msvc
          uses: ilammy/msvc-dev-cmd@v1

        - name: Install xmake
          uses: xmake-io/github-action-setup-xmake@v1

        - name: Configure & Build
          id: confandbuild
          run: |
            $VS_RUNTIME = "MD"
            if("${{ matrix.kind }}" -eq "static") {
                $VS_RUNTIME = "MT"
            }

            if("${{ matrix.os.compiler }}" -eq "MinGW") {
              xrepo install llvm-mingw
              xmake f -v --yes -m ${{ matrix.build_type }} -k ${{ matrix.kind }} -p mingw@llvm-mingw
            else
              xmake f -v --yes -m ${{ matrix.build_type }} -k ${{ matrix.kind }} --vs_runtime=$VS_RUNTIME
            }
            xmake b

        - name: Install
          id: install
          run: |
            xmake install --installdir="${{ runner.workspace }}/StormKit_Output"

            
        - name: Upload artifacts
          id: upload
          uses: actions/upload-artifact@v1
          with:
            name: ${{ matrix.os.name }}-${{ matrix.os.compiler }}-${{ matrix.kind }}-${{ matrix.build_type }}
            path: ${{ runner.workspace }}/StormKit_Output
 